name: CI/CD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test_build:
    name: Testing if the build was successful
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
        
      - run: cd frontend/web
      - run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build_artifact
          path: build/
          
  backend_deploy:
    name: Deploy the backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm run dev # this will fail as i have yet to include the secrets #
      
  frontend_deploy:
    name: Deploy the frontend
    needs: test_build
    runs-on: ubuntu-latest

    steps:
      - run: cd frontend/web
      
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build_artifact
          path: build/

      - name: Deploy the build
        run: node --name "frontend" -- -r dotenv/config build # this will fail as i have yet to include the secrets #
      
